---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: simplewebapp
  namespace: test
  annotations:
    fluxcd.io/automated: "true"
    filter.fluxcd.io/chart-image: glob:production-*
spec:
  releaseName: simplewebapp
  chart:
    git: ssh://git@github.com/Sergeybon/kubernetesconf
    ref: master
    path: charts/simplewebapp
  values:
    image:
      repository: gcr.io/k8ssbondar/github.com/sergeybon/simplewebapp@sha256:3ba6b16a209931c212541c5a92fa8728b394b2106c4bb83b39daedb553efe96f
      tag: "production-8914e6fb0c539681f37b6c25504728b2bc927fe0"
    replicaCount: 1
    service:
      port: 80
    resources:
      requests:
        cpu: "200m"
        memory: "20Mi"
      limits:
        cpu: "400m"
        memory: "64Mi"

