---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: simplewebapp
  namespace: test
  annotations:
    fluxcd.io/automated: "true"
    filter.fluxcd.io/chart-image: glob:production-*
spec:
  releaseName: simplewebapp
  chart:
    git: ssh://git@github.com/Sergeybon/kubernetesconf
    ref: master
    path: charts/simplewebapp
  values:
    image:
      repository: gcr.io/k8ssbondar/github.com/sergeybon/simplewebapp@sha256:f160e206b332bdb1a15b9bfbe97d417f1435e0325a0d4c3c098c04f1a72cebd4
      tag: "production-7140ae898e92a171844a5f91b1193d49e38b7bb1"
    replicaCount: 1
    service:
      port: 80
    resources:
      requests:
        cpu: "200m"
        memory: "20Mi"
      limits:
        cpu: "400m"
        memory: "64Mi"

